/* eslint-disable react/react-in-jsx-scope */

import Register from "./Register";

export const metadata = {
  title: "Spyder",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Register />
    </div>
  );
};

export default page;
