/* eslint-disable react/react-in-jsx-scope */

import Login from "./Login";

export const metadata = {
  title: "Spyder",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Login />
    </div>
  );
};

export default page;
